### ISSUE TITLE
Increase range of threshold sigma parameter

### ISSUE THREAD

**Issue by giuliapaci** [epitools/epitools#131]
The threshold sigma parameter in the segmentation reaches a max value of 999, but background intensity can be larger than this If one is using a 16bit image for example. The maximum value needs to be increased in order to accommodate these images and avoid segmenting background regions in the image.

**Comment by Pablo1990** [comment]
We have two options here:
- Increase the range
- Make it proportional (which is the one that I'm inclined to).

Do you agree or do we want to keep to pixels?
