### ISSUE TITLE
Connecting to napari-tyssue

### ISSUE THREAD

**Issue by kephale** [epitools/epitools#140]
**Is your feature request related to a problem? Please describe.**

Hey Folks, are you all interested in thinking up ways to connect epitools to tyssue and/or napari-tyssue?

I saw @Pablo1990 star our repo, so I thought I'd reach out :)

Cheers,
Kyle

**Comment by Pablo1990** [comment]
Hi Kyle,

Thanks for reaching out! We are very interested actually! Can we have a quick call this week or early next week and talk about our plans? My email is [p.munuera@ucl.ac.uk](mailto:p.munuera@ucl.ac.uk) 

Thanks again!
Pablo
