### ISSUE TITLE
Add option to export graphs created by the Cell Statistics widget

### ISSUE THREAD

**Issue by p-j-smith** [epitools/epitools#50]
The cell statistics themselves can be exported to CSV. However, the graph (network of cell neighbours) at each frame can't yet be saved to file. 

We should add a button 'Export graphs' or 'Export cell networks' to the Cell Statistics widget.

What format should the exported graphs be in? Should there be a separate file for each frame? Or e.g. a numpy array of sparse adjacency matrices - one sparse matrix per frame?

**Comment by Pablo1990** [comment]
This is not really relevant anymore.
